sudo: false
language: node_js
node_js:
- '5.8'
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install
script:
- npm test
cache:
  directories:
  - node_modules
